### ISSUE TITLE
James.Testing.Rest - Todo List

### ISSUE THREAD

**Issue by toddmeinershagen** [QualitySoftwareMatters/James.Testing#2]
- [ ] **QueryString** - Add support for query string assembly for GET requests.
- [ ] **Headers** - Add support for Headers for requests.
- [ ] **Dynamic Body** - Allow for GET request to return dynamic type for easier verification.
- [ ] **Dynamic Error** - Allow for dynamic error message rather than string.  (should be default behavior, if TError not specified.)
## Details

**QueryString**

Should support both api and strongly typed.

Request
  .Get<Person>("http://www.persons.com/api/People")
  .WithQueryStringValue("", "")
  .WithQueryStringValues(new {Id = "", FirstName = ""})
  .Verify(r => r);

http://qa-svc-ei.medassets.com/api/Benefits?payerId=24ecae81-193d-41e2-b22b-e4a36932ac09&subscriberDOB=06%2F25%2F1992&fromDate=9%2F24%2F2013&ProviderName=City%20Of%20Hope&providerId=1750358297&subscriberId=92712515D6&UseCache=false&subscriberLastName=Ayala&subscriberFirstName=Andrew&password=password&serviceTypeCode=30&user=TestConsumer

**Headers**

Should support both api and strongly typed.

Request.
  .Get<Person>("http://www.persons.com/api/People")
  .WithHeader("", "")
  .WithHeaders(new {Id = "", FirstName= ""})
  .Verify(r => r);

x-medassets-auth: source:
871B8C6B-3833-4BF3-B68A-80620966482B|user:dselukha@medassets.com|clientId:99001|homeFacility:|aaaHomeFacility:d179d1ec-77d4-4ed9-b16b-57a6ee1a2578|accessibleFacilities:1235|hasAllFacilityAccess:False

**Dynamic Body**

Request
  .GetAsDynamic("")
  .Verify(r => r);
